#!/usr/bin/env node
var cmds = [];

if (process.argv.length < 3) {
	console.log('Please provide a commit message!');
	process.exit(-1);
}

cmds.push('git add -A');
cmds.push('git commit -m "'+process.argv.slice(2).join(' ')+'"');
cmds.push('git pull');
cmds.push('git push');

require('child_process').execSync(cmds.join(' && '), { stdio: 'inherit' })
